#################National Association of Plant Breeders#################
####                     Annual Poster Competition                  ####
###    Script for Returning Judges Scores and Comments to Students   ###
##                Generated by Amanda M Hulse-Kemp 08/2020            ##
########################################################################


#Starting with a CSV exported from Excel
#MAKE SURE THAT ANY COMMAS "," in Judges Comment section have been replaced in Excel with "." prior to exporting to CSV otherwise will cause issues on exporting those columns here

#MAKE SURE - any students with multiple posters are not present in the same spreadsheet, ie remove one poster with comments and rerun a second time to generate another email
#If student is present multiple times with the same email it will send all comments and scores for multiple posters together

dos2unix *.csv

mk Log.txt
 
cat *.csv | cut -f3 -d , | uniq | grep -v "Email" > UniqueEmails.txt

echo "Step 1" >> Log.txt

for i in $(cat UniqueEmails.txt)
     do
     grep "Student's" *.csv > "$i"
     grep "$i" *.csv >> "$i"
     done


echo "Step 2" >> Log.txt

for i in $(cat UniqueEmails.txt)
      do awk -F, '(NR==1){h4=$4;h5=$5;h6=$6;h7=$7;h8=$8;h9=$9;h10=$10;h11=$11;h12=$12;h13=$13;h14=$14;next} {print "Thank you " $1 " " $2 " for presenting your poster at the National Association of Plant Breeders Annual Conference. This email is to provide feedback from the Judges that analyzed your poster. The final score from each judge was used as raw input in the standardized normalized statistical procedure to determine your final total score in the competition. We hope you enjoyed this years NAPB and look forward to seeing you next year. Any feedback or questions can be sent to NAPBEducation@gmail.com. Sincerely, NAPB Education Committee "}' "$i" > "$i".txt; sed -i '/competition./q' "$i".txt
     done


echo "Step 3" >> Log.txt


for i in $(cat UniqueEmails.txt)
     do awk -F, '(NR==1){h4=$4;h5=$5;h6=$6;h7=$7;h8=$8;h9=$9;h10=$10;h11=$11;h12=$12;h13=$13;h14=$14;next} {print "\n \n" "Scientific Content (x1.5): Sound scientific basis? Appropriate design, controls, and analysis? Proper citation? Results/conclusions address the objective/hypothesis? Novelty?: "$4"\n" "Ability to answer questions, speaking ability, audience engagement (x1): Does the presenter concisely convey the research, why it is important, and what the impacts are? Take home message clearly conveyed?: "$5"\n" "Merit, justification, and feasibility of research (x1): Are there broad implications of the research? Is there an obvious need for the research? Is the objective clearly stated and addressed in the research?: "$6"\n" "Organization and appearance (x1): Appropriate graphics? Neatness? Creativity? Logical sequence? Appropriate proportion of text and figures/tables/graphics?: "$7"\n" "Video presentation skills (refer to 2 minute video in uploads) (x1.5): How are the presenters video skills, creativity in engagement? Did they stay on time?: "$8"\n"  "\n\nAdditional Comments Provided by Judge-\n"  "Scientific content: "$9"\n" "Ability to answer questions, speaking ability, audience engagement: "$10"\n" "Merit, justification, and feasibility of research: "$11"\n" "Organization and appearance (appropriate graphics, neatness, eye-catching, logical sequence): "$12"\n" "Video presentation skills (2 minute uploaded video): "$13"\n" "Additional Comments: "$14"\n\n"}' "$i" >> "$i".txt
     done



echo "Step 4" >> Log.txt


dos2unix *.txt

for i in $(cat UniqueEmails.txt)
    do cat "$i".txt | mail -s "Student Feedback from National Association of Plant Breeders Poster Competition" "$i"
    done


echo "Finished" >> Log.txt
echo date >> Log.txt
